spring:
  application:
    name: tasty-flavors-delivery
  datasource:
    url: jdbc:postgresql://localhost:5432/tasty
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
jwt:
  secret: ba76e755f23bb406c6e33cb18916be32
  expiration: 3600000